version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: challenge
    ports:
      - "3306:3306"

  admin:
    image: adminer
    ports:
      - "8080:8080"
